name: DevOps (CD)

on:
  pull_request:
    types: closed
    branches:
      - master

jobs:
  assemble:
    name: Assemble ðŸš€
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout ðŸ›Žï¸
        uses: actions/checkout@v2

      - name: Assemble and sign APK ðŸ”
        run: |
          mkdir keystore
          echo "$SIGNING_KEY" | base64 --decode > "$SIGNING_KEY_FILE"
          ./gradlew assemble
        env:
          SIGNING_KEY_FILE: ${{ secrets.SIGNING_KEY_FILE }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}

      - name: Archive APK ðŸ“š
        uses: actions/upload-artifact@v2
        with:
          name: LostPets-Android
          path: app/build/outputs/apk/releaseHeroku/LostPets-releaseHeroku.apk