name: DevOps (CI/CD) â˜ï¸

on:
  push:
    branches:
      - master

jobs:
#  code-analysis:
#    name: Code analysis ğŸ”
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Repository checkout ğŸ›ï¸
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#
#      - name: Use JDK 11 âš™ï¸
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#
#      - name: SonarCloud scan ğŸ”
#        run: mvn verify sonar:sonar -DskipTests
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          JASYPT_ENCRYPTOR_PASSWORD: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-test:
    name: Build and test âš™ï¸
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Use JDK 1.8 âš™ï¸
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Kotlin Lint ğŸš¨
        run: ./gradlew ktlintCheck

      - name: Android Lint ğŸ¤–
        run: ./gradlew lint

      - name: Test ğŸ§ª
        run: ./gradlew test
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}

      - name: Assemble âš’ï¸
        run: ./gradlew assemble
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}

      - name: Archive build ğŸ“š
        uses: actions/upload-artifact@v2
        with:
          name: LostPets-Android
          path: app/build/outputs/apk/releaseHeroku/app-releaseHeroku-unsigned.apk

      - name: Build documentation ğŸ“–
        run: ./gradlew dokka

      - name: Archive documentation ğŸ“š
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: app/build/kdoc

      - name: Archive reports ğŸ“š
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: app/build/reports
