name: DevOps (CI/CD) â˜ï¸

on:
  push:
    branches:
      - master

jobs:
  code-analysis:
    name: Code analysis ðŸ”
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout ðŸ›Žï¸
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use JDK 11 âš™
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: SonarCloud scan ðŸ”Ž
        run: ./gradlew sonarqube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-test:
    name: Build and test âš™
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout ðŸ›Žï¸
        uses: actions/checkout@v2

      - name: Use JDK 1.8 âš™
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Kotlin Lint ðŸš¨
        run: ./gradlew ktlintCheck

      - name: Android Lint ðŸ¤–
        run: ./gradlew lint

      - name: Test ðŸ§ª
        run: ./gradlew test

      - name: Build documentation ðŸ“–
        run: ./gradlew dokka

      - name: Archive documentation ðŸ“š
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: app/build/kdoc

      - name: Code coverage â˜‚
        run: ./gradlew jacocoTestReport

      - name: Archive code coverage result ðŸ“š
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: app/build/reports/rep/jacocoTestReport

  assemble:
    name: Assemble ðŸš€
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Repository checkout ðŸ›Žï¸
        uses: actions/checkout@v2

      - name: Assemble and sign APK ðŸ”
        run: |
          mkdir keystore
          echo "$SIGNING_KEY" | base64 --decode > "$SIGNING_KEY_FILE"
          ./gradlew assemble
        env:
          SIGNING_KEY_FILE: ${{ secrets.SIGNING_KEY_FILE }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}

      - name: Archive APK ðŸ“š
        uses: actions/upload-artifact@v2
        with:
          name: LostPets-Android
          path: app/build/outputs/apk/releaseHeroku/LostPets-releaseHeroku.apk
